//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetoConexaoBanco
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public int cod_produto { get; set; }
        public string nome { get; set; }
        public Nullable<int> fk_tipo { get; set; }
    
        public virtual tipo_produto tipo_produto { get; set; }
    }
}
